services:

  frontend:
    container_name: modyx-frontend

    build:
      context: ./front

    image: modyx-frontend

    ports:
      - "127.0.0.1:31000:3000"

    env_file:
      - ./front/.env.production

    restart: unless-stopped


  backend:
    container_name: modyx-backend

    build:
      context: ./back

    image: modyx-backend

    ports:
      - "127.0.0.1:31001:8000"

    env_file:
      - ./back/.env.production

    restart: unless-stopped
